import { SimQuestion } from "./types";

/**
 * 题库 v3.2 — 100 题，基于本地知识库整理
 *
 * 效果区间：
 *   exposure: ±30~±300 (开局基数 1500)
 *   enterConversion: ±0.005~±0.02
 *   orderConversion: ±0.005~±0.02
 *   avgPrice: ±1~±5
 *   badReviewRate: ±0.01~±0.03 (1%~3%)
 *   cash: ±100~±1000
 */
export const QUESTION_BANK: SimQuestion[] = [
  // ========== 一、流量与平台权重 (q001-q015) ==========
  {
    id: "q001",
    day: 1,
    title: "曝光下降了20%",
    desc: "昨天订单比前天少了不少，后台显示曝光掉了。",
    realCase: "闫寒观点：满减是平台权重最直接的杠杆，参与满减的店铺会进入活动池获得额外曝光。但降价不涨曝光，不行动平台判定不活跃。",
    options: [
      { text: "开启满30减5活动", effect: { cash: -300, exposure: 200, orderConversion: 0.01, badReviewRate: 0.01 },
        verdict: "推荐：用杠杆撬流量",
        knowledge: "满减是平台权重最直接的杠杆：参与活动的店铺会进入活动池获得额外曝光，下单门槛感降低也提升下单率。代价是补贴成本和订单密度上升的轻微差评。" },
      { text: "直接降价3元", effect: { cash: -200, orderConversion: 0.015, avgPrice: -3 },
        verdict: "治标不治本",
        knowledge: "降价直接拉下单率（用户决策成本降低），但客单价被永久压低，未来每单都少赚3块，长期毛利受损。" },
      { text: "暂时不动观察", effect: { exposure: -100 },
        verdict: "最危险的选择",
        knowledge: "外卖排名看店铺活跃度，曝光下降时不行动，平台判断你不活跃，曝光会继续掉。" },
    ],
  },
  {
    id: "q002",
    day: 1,
    title: "曝光涨了订单没涨",
    desc: "数据看曝光在涨，但订单纹丝不动。该看哪个指标？",
    realCase: "闫寒观点：双转化率（入店率+下单率）是核心。曝光不等于成交，先看卡在哪一环。",
    options: [
      { text: "查入店率：是不是封面图不行", effect: { cash: -150, enterConversion: 0.015 },
        verdict: "推荐：先诊断再行动",
        knowledge: "曝光不等于成交，先看用户进店率（封面图、店名、评分）。这是双转化诊断的第一环。" },
      { text: "查下单率：是不是菜单结构差", effect: { cash: -200, orderConversion: 0.015 },
        verdict: "对症下药",
        knowledge: "进了店没下单，问题在菜单：排序、套餐、价格锚点。下单率是双转化的第二环。" },
      { text: "无脑加大推广", effect: { cash: -500, exposure: 200 },
        verdict: "方向错了",
        knowledge: "曝光的窟窿不能用更多曝光填，转化没修好，钱白花。" },
    ],
  },
  {
    id: "q003",
    day: 1,
    title: "美团客户经理推点金",
    desc: "客户经理打电话说可以上点金推广。",
    realCase: "闫寒观点：点金推广是最精准的推广方式。所有推广都要和点金比投产比，划算就用不划算就停，没有玄学。",
    options: [
      { text: "试一下，预算300/天", effect: { cash: -300, exposure: 150 },
        verdict: "推荐：用数据说话",
        knowledge: "点金是知识库里被点名最精准的推广方式。300预算约换100次有效进店曝光，是稳妥试水。" },
      { text: "砸大点，预算800/天", effect: { cash: -800, exposure: 350, enterConversion: 0.005 },
        verdict: "新店慎用大预算",
        knowledge: "高预算拿到平台优先位，曝光大涨，且优质流量位用户决策更果断。但点金占实收应控制在2-5%。" },
      { text: "不上，自然流量够", effect: { exposure: -50 },
        verdict: "短期省钱长期亏",
        knowledge: "短期省钱，长期不投意味着权重缓慢下滑。" },
    ],
  },
  {
    id: "q004",
    day: 1,
    title: "铂金展位机会",
    desc: "平台推出铂金展位，列表占更大面积。",
    options: [
      { text: "买，作为补充曝光", effect: { cash: -500, exposure: 200, enterConversion: 0.005 },
        verdict: "推荐：从基础功做起",
        knowledge: "铂金展位定位是补充手段，配合点金更划算，能在列表占更大视觉份额。" },
      { text: "把它当主渠道猛投", effect: { cash: -1000, exposure: 250 },
        verdict: "次优选择",
        knowledge: "铂金展位不是主渠道，把它当唯一打法会发现ROI跑不过点金。" },
      { text: "不买", effect: {},
        verdict: "不如不做",
        knowledge: "不是必需品，但放弃就少一个露脸机会。" },
    ],
  },
  {
    id: "q005",
    day: 1,
    title: "全站推广要不要开",
    desc: "平台全站推广能跨场景投放，价格波动大。",
    options: [
      { text: "算ROI再决定", effect: { cash: -300, exposure: 100 },
        verdict: "推荐：活动池是关键",
        knowledge: "知识库原话：全站推广没有玄学，划算就用，不划算就不用，关键看投产比。" },
      { text: "盲目开大预算", effect: { cash: -800, exposure: 200, badReviewRate: 0.01 },
        verdict: "适合有底气的店",
        knowledge: "不算ROI乱开等于送钱给平台，烧完之后流量回落更难看。" },
      { text: "完全不开", effect: { exposure: -30 },
        verdict: "外卖没有自然流量",
        knowledge: "完全不试就不知道是否划算，错失合适场景。" },
    ],
  },
  {
    id: "q006",
    day: 2,
    title: "新店要做新客定向",
    desc: "你的店开业不久，需要决定推广人群。",
    realCase: "闫寒观点：线下发传单现在反而比线上流量便宜。刚需餐饮的客户就在1-3公里内。",
    options: [
      { text: "重点投新客", effect: { cash: -400, exposure: 200, enterConversion: 0.01 },
        verdict: "推荐：性价比最高",
        knowledge: "知识库明确：开店初期重点投新客，先把基本盘人群打出来，老客之后再说。" },
      { text: "投老客召回", effect: { cash: -300, exposure: 50 },
        verdict: "线上线下结合",
        knowledge: "新店没几个老客，这时候投老客等于白烧。" },
      { text: "平均铺所有人群", effect: { cash: -500, exposure: 100 },
        verdict: "烧钱未必值",
        knowledge: "平均投放=没有重点，效率最低。" },
    ],
  },
  {
    id: "q007",
    day: 2,
    title: "数据下滑要不要老客定向",
    desc: "稳定经营一个月，最近数据开始下滑。",
    options: [
      { text: "加老客定向，把墙头草搂回来", effect: { cash: -350, exposure: 100, orderConversion: 0.01 },
        verdict: "推荐：数据不说谎",
        knowledge: "知识库的原始策略：数据下滑时加老客定向，把摇摆中的老客拉回来比拉新便宜得多。" },
      { text: "继续加大新客投放", effect: { cash: -600, exposure: 150 },
        verdict: "有经验才行",
        knowledge: "拉新成本是召回成本的3-5倍，下滑期不应该烧拉新。" },
      { text: "把所有活动暂停省钱", effect: { exposure: -100, orderConversion: -0.005 },
        verdict: "盲人摸象",
        knowledge: "下滑期紧急刹车反而加速失速，正确做法是切人群不是停活动。" },
    ],
  },
  {
    id: "q008",
    day: 2,
    title: "菜单大改之后",
    desc: "你刚刚把菜单上的爆款全换了。",
    options: [
      { text: "加流失老客定向", effect: { cash: -400, exposure: 100, orderConversion: 0.015 },
        verdict: "最直接有效",
        knowledge: "菜单大改后召回流失老客效率最高，他们对店铺有认知基础，新菜单又给了他们重新尝试的理由。" },
      { text: "只投新客", effect: { cash: -500, exposure: 150 },
        verdict: "推荐：杠杆效应",
        knowledge: "新客不知道你改没改菜单，单位获客成本更高。" },
      { text: "什么都不加", effect: { enterConversion: -0.005 },
        verdict: "短效",
        knowledge: "改菜单不告诉用户=自嗨，转化会受影响。" },
    ],
  },
  {
    id: "q009",
    day: 2,
    title: "霸王餐停了流量就跌",
    desc: "上个月霸王餐拉起来的流量，停了之后又掉回原点。",
    options: [
      { text: "审视基础：菜单+评分+履约", effect: { cash: -300, enterConversion: 0.01, orderConversion: 0.005 },
        verdict: "推荐：标准打法",
        knowledge: "知识库直接点名：霸王餐停了流量就跌=店铺基础有问题，必须先修内功才能稳住流量。" },
      { text: "再开一轮霸王餐", effect: { cash: -600, exposure: 200 },
        verdict: "有创意",
        knowledge: "等于把窟窿越挖越大，停了还是会跌。补贴是兴奋剂不是治本药。" },
      { text: "上更多刷单", effect: { cash: -300, exposure: 100, badReviewRate: 0.02 },
        verdict: "方向对力度小",
        knowledge: "虚假数据会触发平台风控，得不偿失。" },
    ],
  },
  {
    id: "q010",
    day: 2,
    title: "搜索流量高列表流量低",
    desc: "后台发现搜索流量很高，但列表流量异常低。",
    realCase: "闫寒观点：店铺权重越高，推广越便宜。广东湛江粤菜酒楼，220推广出12000实收。",
    options: [
      { text: "查刷单和异常订单源头", effect: { cash: -200, exposure: 100, badReviewRate: -0.01 },
        verdict: "推荐：先练内功",
        knowledge: "知识库明确：搜索高列表低是虚假数据导致的畸形流量表现，必须先拔掉刷单源头。" },
      { text: "无视，能跑就行", effect: { exposure: -150, badReviewRate: 0.01 },
        verdict: "花钱买时间",
        knowledge: "畸形流量会触发平台风控降权，越拖越严重。" },
      { text: "继续加点金", effect: { cash: -500, exposure: 150 },
        verdict: "长期会掉队",
        knowledge: "底层数据有问题再投钱也是白投，平台不会给你正常分配自然流量。" },
    ],
  },
  {
    id: "q011",
    day: 3,
    title: "新客下单率不合格",
    desc: "新客来了不少，但下单率很低，远低于行业。",
    options: [
      { text: "立即改菜单结构和封面", effect: { cash: -300, orderConversion: 0.02 },
        verdict: "推荐：低成本高效",
        knowledge: "知识库强调：新客下单率不合格就要改菜单，不能靠霸王餐硬撑——撑出来的是假数据，停了就没。" },
      { text: "继续撒霸王餐", effect: { cash: -500, exposure: 100, badReviewRate: 0.02 },
        verdict: "投入产出看情况",
        knowledge: "用补贴硬撑下单率是治标不治本，停了立刻原形毕露。" },
      { text: "提价让用户更慎重", effect: { avgPrice: 2, orderConversion: -0.01 },
        verdict: "有钱可以试",
        knowledge: "下单率本来就不行，再提价等于赶客。" },
    ],
  },
  {
    id: "q012",
    day: 3,
    title: "线下传单要不要发",
    desc: "线上推广越来越贵，有人提议线下发传单。",
    realCase: "闫寒观点：求好评比删差评更重要。恶意差评其实是少数，大部分差评是真实体验不好。",
    options: [
      { text: "试一下小区传单", effect: { cash: -200, exposure: 150, enterConversion: 0.005 },
        verdict: "推荐：攻比守重要",
        knowledge: "知识库明确：线下传单现在反而可能比线上更便宜，尤其是社区店有非常具体的辐射范围。" },
      { text: "傲慢不做线下", effect: { exposure: -30 },
        verdict: "合规有效",
        knowledge: "线下传单被很多新老板看不起，正因为如此竞争反而更小。" },
      { text: "全员铺传单大干一周", effect: { cash: -800, exposure: 250 },
        verdict: "治标不治本",
        knowledge: "传单也要算ROI，盲目铺等于线下版无脑投点金。" },
    ],
  },
  {
    id: "q013",
    day: 3,
    title: "平台喜欢什么商家",
    desc: "客户经理告诉你：表现好的店会拿到更多倾斜。",
    options: [
      { text: "稳定接单+减少客诉+留住老客", effect: { cash: -200, exposure: 100, badReviewRate: -0.02, orderConversion: 0.005 },
        verdict: "推荐：效率优先",
        knowledge: "平台缺的是流量不是商家。知识库原话：能帮平台留住老客、减少客诉、提升流量利用率的商家最受平台喜欢。" },
      { text: "猛打价格战吸引下单", effect: { cash: -400, orderConversion: 0.01, avgPrice: -2 },
        verdict: "省小亏大",
        knowledge: "价格战不是平台喜欢的，平台希望流量被高价值地利用。" },
      { text: "经常缺货退单冲销量", effect: { cash: 200, badReviewRate: 0.03, exposure: -100 },
        verdict: "鸵鸟心态",
        knowledge: "缺货退单是平台最恨的'浪费流量'行为，会立刻被降权。" },
    ],
  },
  {
    id: "q014",
    day: 3,
    title: "商圈选址人流vs客流",
    desc: "正在评估一个商铺位置，门口人流很大。",
    realCase: "闫寒的超预期法：一个月的赠品集中一周送完，制造视觉冲击→拍照→分享→优质评论。",
    options: [
      { text: "数人头看真实进店转化", effect: { cash: -100, enterConversion: 0.01 },
        verdict: "推荐：短期集中爆破",
        knowledge: "知识库强调：人流不等于客流，真正能转化的才是客流。要花3天数人头观察。" },
      { text: "人流大就开干", effect: { cash: -500, enterConversion: -0.01 },
        verdict: "合规但衰退中",
        knowledge: "人流不代表客流，盲目押注地段，房租可能高得离谱。" },
      { text: "只看租金最便宜的位置", effect: { exposure: -100 },
        verdict: "成本高见效慢",
        knowledge: "租金便宜往往意味着流量也便宜，知识库里说'租的是流量不是面积'。" },
    ],
  },
  {
    id: "q015",
    day: 3,
    title: "选址主动线vs次动线",
    desc: "商圈里主动线满了，次动线还有便宜的铺。",
    realCase: "闫寒观点：不接单率必须为0。平台缺的是流量不是商家，浪费平台流量会被报复。",
    options: [
      { text: "次动线但加同城推广补量", effect: { cash: -400, exposure: 200, enterConversion: 0.005 },
        verdict: "推荐：这是红线",
        knowledge: "次动线租金便宜但客流弱，配套同城推广补足曝光是知识库的标准打法。" },
      { text: "无脑选主动线最贵铺", effect: { cash: -800 },
        verdict: "治本之道",
        knowledge: "主动线房租高，被流量价值绑架，没有现金缓冲就翻车。" },
      { text: "选商圈死角图便宜", effect: { exposure: -200 },
        verdict: "只能应急",
        knowledge: "动线尾部和死角容易被前端门店截流，知识库明确不推荐。" },
    ],
  },
  // ========== 二、评价与口碑 (q016-q030) ==========
  {
    id: "q016",
    day: 4,
    title: "求好评 vs 删差评",
    desc: "差评多了，店里争论：到底应该求好评还是想办法删差评？",
    options: [
      { text: "重点设计求好评流程", effect: { cash: -100, badReviewRate: -0.02, orderConversion: 0.005 },
        knowledge: "知识库原话：求好评比删差评更高效。差评是删不动的，只能用大量真实好评把它稀释。" },
      { text: "花钱找服务删差评", effect: { cash: -500, badReviewRate: -0.01 },
        knowledge: "删差评成本高、难度大，且平台风控严，性价比极低。" },
      { text: "什么都不做", effect: { badReviewRate: 0.01 },
        knowledge: "评价是经营工具，放任不管=主动放弃口碑增长。" },
    ],
  },
  {
    id: "q017",
    day: 4,
    title: "评价得券设计",
    desc: "想用一次券换一次好评，怎么设计？",
    options: [
      { text: "下次5元无门槛券", effect: { cash: -200, badReviewRate: -0.02, orderConversion: 0.01 },
        knowledge: "知识库标准模型：评价得券=拿走好评+锁定一次复购，一举两得。" },
      { text: "10元满50减券", effect: { cash: -150, badReviewRate: -0.01 },
        knowledge: "门槛太高用户不来，券约等于废纸，效率打折。" },
      { text: "现金返现5元", effect: { cash: -300, badReviewRate: -0.02 },
        knowledge: "现金不锁复购，钱花了人也不一定回来。" },
    ],
  },
  {
    id: "q018",
    day: 4,
    title: "超预期法集中送",
    desc: "想让用户记住你，准备送点小东西。",
    options: [
      { text: "随机给老客突然送一罐饮料", effect: { cash: -250, badReviewRate: -0.02, orderConversion: 0.01 },
        knowledge: "知识库'超预期法'：意料之外的小礼物比固定赠品更打动人，记忆点强。" },
      { text: "每单都送一颗糖", effect: { cash: -150 },
        knowledge: "固定赠品会被习惯化，没有惊喜感，等于成本不出效果。" },
      { text: "什么都不送省钱", effect: {},
        knowledge: "成本省了，但用户记不住你。" },
    ],
  },
  {
    id: "q019",
    day: 4,
    title: "视觉冲击送一桌",
    desc: "想做一次能让用户拍照分享的体验。",
    options: [
      { text: "团餐多送一份'彩头菜'摆满桌", effect: { cash: -400, exposure: 200, badReviewRate: -0.02 },
        knowledge: "知识库'视觉冲击法'：让顾客看到一桌惊艳的菜，主动拍照传播。送一份比打折更出圈。" },
      { text: "打八折更直接", effect: { cash: -300, orderConversion: 0.01, avgPrice: -2 },
        knowledge: "打折用户感知不强，没有视觉爆点，不会主动传播。" },
      { text: "什么都不做", effect: {},
        knowledge: "错过一次免费传播机会。" },
    ],
  },
  {
    id: "q020",
    day: 4,
    title: "邻里柠檬茶送小鸭子",
    desc: "对面新开邻里柠檬茶，给每杯送只小黄鸭。",
    options: [
      { text: "学他们做'记忆赠品'", effect: { cash: -300, exposure: 150, badReviewRate: -0.01 },
        knowledge: "知识库案例：邻里柠檬茶送小鸭子让所有用户记住品牌。记忆赠品=便宜的品牌资产。" },
      { text: "笑话他们幼稚", effect: { exposure: -50 },
        knowledge: "小看创意=小看用户传播力，对手在抢你的心智份额。" },
      { text: "学一半送贴纸", effect: { cash: -150, badReviewRate: -0.005 },
        knowledge: "贴纸成本低但仪式感弱，不如鸭子有传播力。" },
    ],
  },
  {
    id: "q021",
    day: 5,
    title: "复购的三个要素",
    desc: "想抓复购，先抓什么？",
    options: [
      { text: "口味稳定+履约准时+评价好", effect: { cash: -200, badReviewRate: -0.02, orderConversion: 0.01 },
        knowledge: "知识库三要素：稳定的口味、准时的履约、可见的好评。少一个复购就崩。" },
      { text: "猛打折扣吸引复购", effect: { cash: -400, orderConversion: 0.01, avgPrice: -2 },
        knowledge: "靠打折换的复购，停了就没。基本盘没修，钱白花。" },
      { text: "上新菜冲击老客", effect: { cash: -300, orderConversion: 0.005 },
        knowledge: "上新菜不解决稳定性问题，老客流失原因不是缺新意。" },
    ],
  },
  {
    id: "q022",
    day: 5,
    title: "客诉率突然上升",
    desc: "客诉量这周比上周翻倍，原因不明。",
    options: [
      { text: "立即排查履约和品控", effect: { cash: -300, badReviewRate: -0.03, orderConversion: 0.005 },
        knowledge: "知识库强调：客诉是最贵的信号，背后藏的是流量浪费、平台降权、口碑下滑三个连锁问题。" },
      { text: "客服硬杠用户", effect: { badReviewRate: 0.03 },
        knowledge: "硬杠会被用户截图发社交媒体，二次伤害更狠。" },
      { text: "多送券摆平", effect: { cash: -400, badReviewRate: -0.01 },
        knowledge: "送券治标不治本，下次该投诉还会投诉。" },
    ],
  },
  {
    id: "q023",
    day: 5,
    title: "差评回复怎么写",
    desc: "刚收到一条差评，店长不知道怎么回。",
    options: [
      { text: "公开诚恳致歉+具体改进", effect: { cash: -50, badReviewRate: -0.02, enterConversion: 0.005 },
        knowledge: "差评回复是给后续看店人看的：诚恳态度+具体改进方案能挽回入店率。" },
      { text: "模板复制粘贴", effect: { badReviewRate: 0.005 },
        knowledge: "模板回复让用户觉得你不重视，看店的新客会担心同样遭遇。" },
      { text: "和用户对线辩解", effect: { badReviewRate: 0.03, enterConversion: -0.01 },
        knowledge: "对线=商家形象崩塌，知识库明确禁止。" },
    ],
  },
  {
    id: "q024",
    day: 5,
    title: "优质评论引导",
    desc: "想让顾客留更有价值的好评，怎么引导？",
    options: [
      { text: "餐盒卡片提示'描述菜品味道'", effect: { cash: -100, badReviewRate: -0.01, enterConversion: 0.005 },
        knowledge: "有具体内容的好评对新客决策影响更大，知识库的'优质评论引导法'。" },
      { text: "求'5星好评'四个字", effect: { cash: -50, badReviewRate: -0.005 },
        knowledge: "光打星没内容，对新客说服力弱，平台权重也低。" },
      { text: "什么都不引导", effect: {},
        knowledge: "好评质量直接影响新客转化，错失机会。" },
    ],
  },
  {
    id: "q025",
    day: 5,
    title: "准时宝要不要开",
    desc: "平台让你开准时宝，超时赔付。",
    options: [
      { text: "开，作为信任背书", effect: { cash: -100, enterConversion: 0.01, badReviewRate: -0.01 },
        knowledge: "准时宝是入店转化的'信任徽章'，知识库明确：能加的认证都加上，平台权重也会更高。" },
      { text: "不开怕赔付", effect: { enterConversion: -0.005 },
        knowledge: "你怕赔付意味着履约不稳，本质是后厨问题不是要不要开的问题。" },
      { text: "开了又不修后厨", effect: { cash: -300, badReviewRate: 0.02 },
        knowledge: "开了准时宝又不解决出餐速度，等着不停赔付。" },
    ],
  },
  {
    id: "q026",
    day: 5,
    title: "产品稳定性",
    desc: "顾客反馈：你家味道每次都不一样。",
    options: [
      { text: "立即SOP化所有出品", effect: { cash: -300, badReviewRate: -0.03, orderConversion: 0.01 },
        knowledge: "知识库铁律：外卖最值钱的是'稳定'。SOP化后味道一致，复购自然涨。" },
      { text: "靠厨师手感", effect: { badReviewRate: 0.02 },
        knowledge: "手感波动=口味波动=口碑波动，这是连锁餐饮的死穴。" },
      { text: "每天换菜单", effect: { cash: -200, badReviewRate: 0.01 },
        knowledge: "频繁换=没有招牌，用户记不住。" },
    ],
  },
  {
    id: "q027",
    day: 5,
    title: "单次补偿 vs 持续体验",
    desc: "用户投诉，到底是补偿一次了事还是改流程？",
    options: [
      { text: "立即补偿+从根源改流程", effect: { cash: -300, badReviewRate: -0.02, orderConversion: 0.005 },
        knowledge: "知识库观点：单次补偿是止血，持续体验才是治病。两手都要做。" },
      { text: "只补偿一次了事", effect: { cash: -150 },
        knowledge: "下次还会犯同样错误，差评重复出现。" },
      { text: "只口头道歉", effect: { badReviewRate: 0.01 },
        knowledge: "用户感知是'你不重视'，下次直接给一星。" },
    ],
  },
  {
    id: "q028",
    day: 5,
    title: "评价是经营工具",
    desc: "新员工把评价当客服任务在处理。",
    options: [
      { text: "把评价系统改造成产品反馈池", effect: { cash: -100, badReviewRate: -0.02, enterConversion: 0.005 },
        knowledge: "知识库：评价不是客服而是经营工具，里面有最便宜的市场调研和最直接的产品建议。" },
      { text: "评价丢给客服", effect: {},
        knowledge: "评价里的金子被埋了，相当于扔掉免费数据。" },
      { text: "屏蔽所有评价", effect: { badReviewRate: 0.02, enterConversion: -0.01 },
        knowledge: "屏蔽=自欺欺人，平台风控也会扣分。" },
    ],
  },
  {
    id: "q029",
    day: 5,
    title: "长期评分先抓什么",
    desc: "想让评分稳定在4.8以上。",
    options: [
      { text: "先抓后厨稳定性", effect: { cash: -300, badReviewRate: -0.02, orderConversion: 0.005 },
        knowledge: "知识库铁律：评分崩=后厨崩。先稳定出品，再谈服务和包装。" },
      { text: "先抓包装颜值", effect: { cash: -200, enterConversion: 0.005 },
        knowledge: "包装好但味道不稳，差评还是来。" },
      { text: "先抓客服话术", effect: { cash: -100 },
        knowledge: "话术救不了产品问题。" },
    ],
  },
  {
    id: "q030",
    day: 5,
    title: "主动设计邀评",
    desc: "想设计一个固定的邀评动作。",
    options: [
      { text: "出餐时夹卡片+扫码送券", effect: { cash: -200, badReviewRate: -0.02, orderConversion: 0.01 },
        knowledge: "知识库标准动作：邀评必须主动设计，不能等用户自发。卡片+小利益=最高效组合。" },
      { text: "短信群发求评", effect: { cash: -100 },
        knowledge: "短信打开率低，效果远不如餐内卡片。" },
      { text: "什么都不做等自来", effect: {},
        knowledge: "外卖用户主动评价的不到5%，等于放弃。" },
    ],
  },
  // ========== 三、后厨与履约 (q031-q042) ==========
  {
    id: "q031",
    title: "高峰期出餐慢",
    desc: "中午高峰出餐时间从15分钟拖到25分钟。",
    options: [
      { text: "梳理SOP+预制半成品", effect: { cash: -400, badReviewRate: -0.02, orderConversion: 0.005 },
        knowledge: "知识库：高峰出餐慢的本质是流程不顺，预制+SOP是唯一解，加人只是缓兵之计。" },
      { text: "再招一个厨师", effect: { cash: -800 },
        knowledge: "人加进来流程不顺还是慢，人力成本永久上升。" },
      { text: "减菜单只留爆款", effect: { avgPrice: -2, orderConversion: 0.005 },
        knowledge: "可行但需要谨慎砍单，砍多了客单结构崩。" },
    ],
  },
  {
    id: "q032",
    title: "外卖菜单瘦身",
    desc: "菜单上有30个菜，一半很少有人点。",
    options: [
      { text: "下架长尾，专注10个爆款", effect: { cash: -100, orderConversion: 0.015, badReviewRate: -0.01 },
        knowledge: "知识库：外卖菜单越精越快越稳。长尾菜品占用后厨注意力，导致核心爆款品质下降。" },
      { text: "加更多新菜测试", effect: { cash: -300, badReviewRate: 0.01 },
        knowledge: "菜越多后厨越乱，不是问题答案。" },
      { text: "保持原样", effect: { badReviewRate: 0.005 },
        knowledge: "现状是问题本身，维持等于退步。" },
    ],
  },
  {
    id: "q033",
    title: "包装漏汤",
    desc: "本周漏汤投诉占了差评的一半。",
    options: [
      { text: "立即换密封餐盒", effect: { cash: -300, badReviewRate: -0.03, orderConversion: 0.005 },
        knowledge: "包装是外卖的'最后一公里'，餐盒小钱省不得，差评赔偿和复购损失更贵。" },
      { text: "贴张'轻拿轻放'纸条", effect: { cash: -50, badReviewRate: -0.005 },
        knowledge: "纸条挡不住物理冲击，治标不治本。" },
      { text: "怼骑手没拿稳", effect: { badReviewRate: 0.02 },
        knowledge: "骑手会差评回去，骑手评分崩=配送时长崩。" },
    ],
  },
  {
    id: "q034",
    title: "出餐时间预报",
    desc: "想让用户对等餐时间有预期。",
    options: [
      { text: "在菜单上显示预计出餐时长", effect: { cash: -50, enterConversion: 0.005, badReviewRate: -0.01 },
        knowledge: "心理学：被告知等待比意外等待焦虑感低很多，差评会下降。" },
      { text: "故意标短让用户更愿下单", effect: { orderConversion: 0.005, badReviewRate: 0.02 },
        knowledge: "短期订单涨，长期差评爆表，用户被骗一次就走。" },
      { text: "不标省事", effect: {},
        knowledge: "错失一个免费优化用户体验的机会。" },
    ],
  },
  {
    id: "q035",
    title: "高峰餐前预制",
    desc: "高峰前一小时是冲刺备餐还是接散客？",
    options: [
      { text: "停接散客全力备爆款半成品", effect: { cash: -100, badReviewRate: -0.02, orderConversion: 0.01 },
        knowledge: "知识库：高峰前的备餐质量直接决定高峰履约。散客赚的钱远低于高峰差评赔的钱。" },
      { text: "继续接散客", effect: { cash: 100, badReviewRate: 0.02 },
        knowledge: "高峰来临时手忙脚乱，差评爆发。" },
      { text: "全员吃饭休息", effect: { cash: 50, badReviewRate: 0.03 },
        knowledge: "毫无准备的高峰=灾难现场。" },
    ],
  },
  {
    id: "q036",
    title: "出餐温度问题",
    desc: "用户反馈到手凉了。",
    options: [
      { text: "保温袋+出餐贴时间标签", effect: { cash: -200, badReviewRate: -0.02 },
        knowledge: "外卖热度是体验关键，保温措施成本低收益高。" },
      { text: "怪天气", effect: { badReviewRate: 0.01 },
        knowledge: "用户不关心天气，只关心到手温度。" },
      { text: "出餐时间提前", effect: { badReviewRate: 0.01 },
        knowledge: "提前出餐反而让食物在保温箱里更久变质。" },
    ],
  },
  {
    id: "q037",
    title: "骑手配送评分低",
    desc: "你家被骑手打了低分，导致接单慢。",
    options: [
      { text: "出餐前主动核对+整理好挂袋", effect: { cash: -100, badReviewRate: -0.01, orderConversion: 0.005 },
        knowledge: "知识库：骑手是隐形顾客，他们的体验直接影响配送时长和接单率。" },
      { text: "无视骑手", effect: { badReviewRate: 0.02 },
        knowledge: "骑手不愿接你的单，配送时长崩，平台权重也会掉。" },
      { text: "和骑手吵架", effect: { badReviewRate: 0.03 },
        knowledge: "骑手集体打低分，你将进入'黑店'循环。" },
    ],
  },
  {
    id: "q038",
    title: "食材库存波动",
    desc: "最近食材采购成本飙升20%。",
    options: [
      { text: "重谈供应商+调整爆款配方", effect: { cash: -200, badReviewRate: -0.005 },
        knowledge: "知识库：食材成本就是利润，重谈供应商和小幅调整配方是长期能力。" },
      { text: "立刻提价转嫁", effect: { avgPrice: 2, orderConversion: -0.01 },
        knowledge: "成本一波动就提价，用户会把你和'乱涨价'绑定。" },
      { text: "用更便宜次品食材", effect: { cash: 200, badReviewRate: 0.03 },
        knowledge: "食材降级=口味降级=口碑崩，得不偿失。" },
    ],
  },
  {
    id: "q039",
    title: "招牌菜品质波动",
    desc: "招牌菜最近时好时坏。",
    options: [
      { text: "招牌菜专人专做+定期盲测", effect: { cash: -300, badReviewRate: -0.02, orderConversion: 0.01 },
        knowledge: "知识库：招牌菜是品牌脊梁，必须独立SOP和品控。" },
      { text: "招牌菜大家轮着做", effect: { badReviewRate: 0.02 },
        knowledge: "轮做=波动，外卖最怕的就是不稳定。" },
      { text: "下架招牌菜", effect: { exposure: -150, orderConversion: -0.01 },
        knowledge: "招牌菜是流量入口，下架=自断流量。" },
    ],
  },
  {
    id: "q040",
    title: "退单率上升",
    desc: "本周退单率从1%涨到5%。",
    options: [
      { text: "查缺货+菜单同步+出餐速度", effect: { cash: -200, badReviewRate: -0.02, exposure: 50 },
        knowledge: "知识库：退单率是平台风控的高敏指标，涨上去会被立即降权。" },
      { text: "无视小事", effect: { exposure: -150, badReviewRate: 0.01 },
        knowledge: "退单是对平台流量的浪费，平台扣分最狠。" },
      { text: "故意拖单让用户取消", effect: { badReviewRate: 0.03, exposure: -100 },
        knowledge: "用户取消你也要承担差评，这是双重损失。" },
    ],
  },
  {
    id: "q041",
    title: "后厨人手不足",
    desc: "新店刚开业，后厨只有2个人。",
    options: [
      { text: "限制接单量保品质", effect: { cash: -100, badReviewRate: -0.02 },
        knowledge: "知识库：开业初期宁愿接少不要接砸，差评一旦累积就难恢复。" },
      { text: "全部接下硬扛", effect: { cash: 200, badReviewRate: 0.03 },
        knowledge: "硬扛带来的差评会让接下来一个月都翻不了身。" },
      { text: "立即招2人", effect: { cash: -800 },
        knowledge: "新店现金紧，盲目扩人可能拖垮现金流。" },
    ],
  },
  {
    id: "q042",
    title: "夜班订单要不要接",
    desc: "夜里22点以后还有零星订单。",
    options: [
      { text: "评估人力成本算ROI再决定", effect: { cash: -100 },
        knowledge: "知识库：每个时段都要算账。夜班订单稀，但夜班人力贵，要看ROI。" },
      { text: "全开24小时", effect: { cash: -600, badReviewRate: 0.01 },
        knowledge: "通宵开店人力成本爆炸，少量订单覆盖不了。" },
      { text: "全部关闭", effect: { exposure: -50 },
        knowledge: "完全不做夜单等于放弃一个差异化时段。" },
    ],
  },
  // ========== 四、客单结构与定价 (q043-q054) ==========
  {
    id: "q043",
    title: "提客单价的安全方式",
    desc: "想把客单价从25提到30。",
    options: [
      { text: "推高毛利套餐+加购小食", effect: { cash: -100, avgPrice: 4, orderConversion: 0.005 },
        knowledge: "知识库：抬客单的正确方式是套餐和加购，不是直接提价。用户感知是'划算'不是'变贵'。" },
      { text: "直接每个菜涨5元", effect: { avgPrice: 5, orderConversion: -0.02 },
        knowledge: "硬涨价会被用户立刻感知，下单率断崖式下跌。" },
      { text: "提包装费", effect: { cash: 100, avgPrice: 1, badReviewRate: 0.01 },
        knowledge: "包装费是用户最敏感的'隐藏费用'，差评高发区。" },
    ],
  },
  {
    id: "q044",
    title: "套餐比例失衡",
    desc: "套餐毛利低，单点毛利高，但用户都点套餐。",
    options: [
      { text: "重做套餐组合提毛利", effect: { cash: -200, avgPrice: 2, orderConversion: 0.005 },
        knowledge: "知识库：套餐是流量品，必须严格设计组合让平均毛利不低于单点的80%。" },
      { text: "下架所有套餐", effect: { orderConversion: -0.02, exposure: -100 },
        knowledge: "套餐是入门钩子，下架=用户失去试错入口，订单暴跌。" },
      { text: "套餐再降价吸引人", effect: { cash: -300, orderConversion: 0.01, avgPrice: -3 },
        knowledge: "毛利更低，越卖越亏。" },
    ],
  },
  {
    id: "q045",
    title: "定价心理锚",
    desc: "新菜单要写定价。",
    options: [
      { text: "设置一个高价'锚定菜'", effect: { cash: -50, avgPrice: 2, enterConversion: 0.005 },
        knowledge: "心理锚定原理：菜单上有一道高价菜，会让其他菜显得便宜。知识库经典套路。" },
      { text: "全部菜价整齐划一", effect: {},
        knowledge: "缺少对比，用户感知不到性价比。" },
      { text: "全部菜超低价", effect: { avgPrice: -3, orderConversion: 0.01 },
        knowledge: "客单价崩，毛利没有，店铺撑不起来。" },
    ],
  },
  {
    id: "q046",
    title: "满减阶梯设计",
    desc: "想做满减活动。",
    options: [
      { text: "设阶梯：满20减2/满35减5/满50减8", effect: { cash: -200, avgPrice: 3, orderConversion: 0.005 },
        knowledge: "阶梯满减的本质是诱导加购，让客单价被推高，比单档满减效率高。" },
      { text: "只设单档满30减5", effect: { cash: -150, orderConversion: 0.005 },
        knowledge: "单档满减没有引导上一档的动机，浪费一次抬客单的机会。" },
      { text: "无满减", effect: { exposure: -100 },
        knowledge: "无满减在外卖排名会被压下去，平台不喜欢。" },
    ],
  },
  {
    id: "q047",
    title: "餐+饮料的组合",
    desc: "想推餐+饮料组合。",
    options: [
      { text: "饮料毛利60%+组合价划算", effect: { cash: -100, avgPrice: 3, orderConversion: 0.005 },
        knowledge: "饮料毛利极高，组合销售=拉客单又拉毛利，知识库经典打法。" },
      { text: "饮料单独打折", effect: { cash: -150, orderConversion: 0.005 },
        knowledge: "单独打折饮料会被单点带走，丢掉组合溢价。" },
      { text: "不卖饮料怕麻烦", effect: { avgPrice: -1 },
        knowledge: "放弃毛利最高的品类，可惜了。" },
    ],
  },
  {
    id: "q048",
    title: "招牌菜赋名权",
    desc: "想给招牌菜起个特别的名字。",
    options: [
      { text: "用'店长私房'+'三年回头客'文案", effect: { cash: -50, enterConversion: 0.005, orderConversion: 0.005 },
        knowledge: "命名是免费杠杆，'招牌''必点''好评第一'这类标签能让下单率提升。" },
      { text: "保留原名", effect: {},
        knowledge: "错失一次免费提转化的机会。" },
      { text: "起个生僻文艺名", effect: { enterConversion: -0.005 },
        knowledge: "看不懂的名字让用户决策卡顿，下单率反而降。" },
    ],
  },
  {
    id: "q049",
    title: "外卖菜单首屏",
    desc: "用户进店前4个菜决定他下不下单。",
    options: [
      { text: "首屏放招牌+套餐+爆款图", effect: { cash: -100, orderConversion: 0.015 },
        knowledge: "首屏是黄金位，必须放最强招牌。知识库：用户翻第二屏的概率不到30%。" },
      { text: "首屏放新品测试", effect: { orderConversion: -0.005 },
        knowledge: "新品没有数据背书，首屏放新品=拿黄金位赌博。" },
      { text: "随便排", effect: { orderConversion: -0.01 },
        knowledge: "顺序就是转化，不排=放弃转化。" },
    ],
  },
  {
    id: "q050",
    title: "高价菜要不要保留",
    desc: "菜单上有一道68元的招牌，月销才10单。",
    options: [
      { text: "保留作为锚定+撑客单", effect: { avgPrice: 1, enterConversion: 0.005 },
        knowledge: "高价菜的价值不是销量是锚定，让其他菜看起来便宜。知识库经典。" },
      { text: "下架腾位", effect: { avgPrice: -1, orderConversion: -0.005 },
        knowledge: "下架等于自降价格上限。" },
      { text: "降到38元增量", effect: { cash: 200, avgPrice: -2 },
        knowledge: "降价后客单结构整体被压低，得不偿失。" },
    ],
  },
  {
    id: "q051",
    title: "包装费定价",
    desc: "包装费是收1元、2元还是免？",
    options: [
      { text: "包装费1元+提到菜单价里", effect: { cash: 50, badReviewRate: -0.005 },
        knowledge: "知识库：包装费是用户敏感点，能藏到菜单价里就藏，明面尽量低。" },
      { text: "明收3元", effect: { cash: 150, badReviewRate: 0.02 },
        knowledge: "包装费高=差评高发地，用户会觉得'被宰'。" },
      { text: "包装费免", effect: { cash: -100, orderConversion: 0.005 },
        knowledge: "完全免会让你的毛利受损，不建议。" },
    ],
  },
  {
    id: "q052",
    title: "新品试水定价",
    desc: "新品上架，定18还是24？",
    options: [
      { text: "首周低价18试水+反馈后调价", effect: { cash: -200, orderConversion: 0.01, avgPrice: -1 },
        knowledge: "知识库：新品先用低价跑数据，验证之后再调到正常价。试水定价是常规打法。" },
      { text: "直接定24", effect: { orderConversion: -0.005, avgPrice: 1 },
        knowledge: "没数据没口碑，定高价没人点。" },
      { text: "定12赔本赚吆喝", effect: { cash: -300, orderConversion: 0.01, avgPrice: -3 },
        knowledge: "太低没有调价空间，调上去用户立刻觉得贵。" },
    ],
  },
  {
    id: "q053",
    title: "客单价跌了2元",
    desc: "本周客单价不知不觉跌了2块。",
    options: [
      { text: "查满减深度+套餐占比", effect: { cash: -100, avgPrice: 2, orderConversion: 0.005 },
        knowledge: "客单价滑落多半是满减或套餐占比上升，要回头收紧活动力度。" },
      { text: "继续加大满减", effect: { cash: -300, avgPrice: -2 },
        knowledge: "越加越跌，雪上加霜。" },
      { text: "不管", effect: { avgPrice: -1 },
        knowledge: "客单价是利润根基，不管=持续亏损。" },
    ],
  },
  {
    id: "q054",
    title: "高客单菜上首位",
    desc: "本想用爆款拉曝光，但毛利低。",
    options: [
      { text: "首位放高毛利组合+第二位放爆款", effect: { avgPrice: 2, orderConversion: 0.005 },
        knowledge: "首位流量最大，要把利润最高的产品放在最显眼位置。" },
      { text: "首位放低价爆款拉量", effect: { orderConversion: 0.01, avgPrice: -2 },
        knowledge: "拉来的都是低价单，毛利低，越卖越亏。" },
      { text: "首位放新品", effect: { orderConversion: -0.005 },
        knowledge: "新品没数据没评分，首位资源浪费。" },
    ],
  },
  // ========== 五、留存与复购 (q055-q066) ==========
  {
    id: "q055",
    title: "首单转复购",
    desc: "新客下单一次后大半都不再来。",
    options: [
      { text: "首单赠下次5元券+加入会员包", effect: { cash: -200, orderConversion: 0.01, badReviewRate: -0.005 },
        knowledge: "知识库：第一单的钩子是把陌生客变熟客最低成本的动作，券+会员是标配。" },
      { text: "首单送大礼包", effect: { cash: -400, orderConversion: 0.005 },
        knowledge: "成本太高，ROI不一定划算。" },
      { text: "什么都不送", effect: {},
        knowledge: "新客来一次不留=每次都在重新拉新，最贵的打法。" },
    ],
  },
  {
    id: "q056",
    title: "会员日设计",
    desc: "想做一个固定的会员日。",
    options: [
      { text: "周三会员日+专属菜+专属价", effect: { cash: -200, orderConversion: 0.01, exposure: 100 },
        knowledge: "会员日的核心是给老客一个回来的理由，知识库提倡固定日+专属感。" },
      { text: "天天打会员折", effect: { cash: -400, avgPrice: -2 },
        knowledge: "天天打折等于没有折，老客会习以为常。" },
      { text: "搞一次性大促", effect: { cash: -300, exposure: 100 },
        knowledge: "一次性活动没有持续记忆点。" },
    ],
  },
  {
    id: "q057",
    title: "老客流失预警",
    desc: "30天没回购的用户越来越多。",
    options: [
      { text: "做'30天未回购'专项召回", effect: { cash: -300, exposure: 100, orderConversion: 0.01 },
        knowledge: "知识库：老客一旦超过45天不回头就难召回，30天是抢救黄金期。" },
      { text: "等他们自己回来", effect: { exposure: -50 },
        knowledge: "用户的时间窗口是有限的，等=主动放弃。" },
      { text: "群发广告短信", effect: { cash: -200, badReviewRate: 0.01 },
        knowledge: "短信是骚扰，被屏蔽率高，反而引发反感。" },
    ],
  },
  {
    id: "q058",
    title: "积分体系怎么做",
    desc: "想做积分体系。",
    options: [
      { text: "1元1分+50分换小食", effect: { cash: -150, orderConversion: 0.005, badReviewRate: -0.005 },
        knowledge: "积分要小步快跑，门槛低，让用户能在短期内兑换到东西。" },
      { text: "积分门槛设到500", effect: {},
        knowledge: "门槛太高用户失去兴趣，等于没做。" },
      { text: "不做积分", effect: {},
        knowledge: "错失一种锁定老客的轻量化工具。" },
    ],
  },
  {
    id: "q059",
    title: "私域社群",
    desc: "想把外卖用户拉到私域。",
    options: [
      { text: "餐内卡片+加群送菜", effect: { cash: -200, exposure: 100, orderConversion: 0.005 },
        knowledge: "私域是知识库提倡的'第二阵地'，把流量从平台转到自己手里。" },
      { text: "硬塞二维码", effect: { badReviewRate: 0.01 },
        knowledge: "硬塞用户反感，反而被举报。" },
      { text: "不做私域", effect: {},
        knowledge: "永远依赖平台流量，议价权为0。" },
    ],
  },
  {
    id: "q060",
    title: "复购券核销率低",
    desc: "送了一堆券，没几个人用。",
    options: [
      { text: "缩短有效期+到期前一天提醒", effect: { cash: -100, orderConversion: 0.01 },
        knowledge: "知识库：券的核销率核心在'紧迫感'，长期券=被遗忘券。" },
      { text: "再加大面额", effect: { cash: -300, orderConversion: 0.005 },
        knowledge: "核销问题不是面额问题，是提醒和门槛问题。" },
      { text: "干脆不送了", effect: { orderConversion: -0.005 },
        knowledge: "完全不送=放弃复购钩子。" },
    ],
  },
  {
    id: "q061",
    title: "回访电话",
    desc: "想给前10%的老客打回访电话。",
    options: [
      { text: "店长亲自电话+小礼包", effect: { cash: -300, badReviewRate: -0.02, orderConversion: 0.01 },
        knowledge: "知识库：高净值老客的'人情账户'是最高ROI的留存动作，店长亲自做。" },
      { text: "客服模板回访", effect: { cash: -100 },
        knowledge: "模板回访的诚意打折，效率不高。" },
      { text: "不回访", effect: {},
        knowledge: "20%的老客贡献80%的营业额，不维护=主动流失。" },
    ],
  },
  {
    id: "q062",
    title: "节日营销",
    desc: "中秋节快到了。",
    options: [
      { text: "做应景套餐+会员专属", effect: { cash: -200, exposure: 150, orderConversion: 0.01 },
        knowledge: "节点营销让用户对店铺产生'记得我'的认知，知识库经典动作。" },
      { text: "全场打8折大促", effect: { cash: -400, orderConversion: 0.005, avgPrice: -2 },
        knowledge: "节点不是促销节，是关怀节。打折反而稀释品牌。" },
      { text: "什么都不做", effect: { exposure: -50 },
        knowledge: "错过一次免费的'我记得你'机会。" },
    ],
  },
  {
    id: "q063",
    title: "用户画像分层",
    desc: "想对老客分层运营。",
    options: [
      { text: "按月消费分3档差异化运营", effect: { cash: -200, orderConversion: 0.01 },
        knowledge: "知识库：分层是精细化运营的起点，VIP和普通客的玩法完全不同。" },
      { text: "所有客一视同仁", effect: {},
        knowledge: "高净值用户被泛运营会觉得没有专属感，慢慢流失。" },
      { text: "只服务VIP", effect: { exposure: -100 },
        knowledge: "忽略中长尾用户=放弃增长池。" },
    ],
  },
  {
    id: "q064",
    title: "续命大额券",
    desc: "想给沉睡用户大力召回。",
    options: [
      { text: "10元无门槛券+限7天", effect: { cash: -300, exposure: 100, orderConversion: 0.01 },
        knowledge: "沉睡用户唤醒成本高，必须用强力券+紧迫感。" },
      { text: "5元有门槛券", effect: { cash: -150 },
        knowledge: "门槛券对沉睡用户拉力不够。" },
      { text: "不召回", effect: {},
        knowledge: "等沉睡变流失=完全损失。" },
    ],
  },
  {
    id: "q065",
    title: "社群活跃度",
    desc: "私域群越来越冷。",
    options: [
      { text: "每天定时福利+群专属菜", effect: { cash: -200, orderConversion: 0.005, exposure: 50 },
        knowledge: "社群活跃靠运营节奏，知识库：定时福利+专属感是激活两板斧。" },
      { text: "群内不停发广告", effect: { badReviewRate: 0.01 },
        knowledge: "群被广告污染，用户屏蔽或退群。" },
      { text: "不管让群自然死亡", effect: {},
        knowledge: "私域阵地变废墟，所有前期投入归零。" },
    ],
  },
  {
    id: "q066",
    title: "邀请新客返利",
    desc: "想做老带新。",
    options: [
      { text: "老客邀新双方各得5元券", effect: { cash: -300, exposure: 150, orderConversion: 0.005 },
        knowledge: "老带新是低成本拉新方式，知识库：用老客信用为新客背书，转化最高。" },
      { text: "只奖励老客", effect: { cash: -200 },
        knowledge: "新客没动力点开链接，转化低。" },
      { text: "不做", effect: {},
        knowledge: "免费的口碑传播池被浪费。" },
    ],
  },
  // ========== 六、选址与商圈 (q067-q074) ==========
  {
    id: "q067",
    title: "选址辐射半径",
    desc: "外卖店辐射半径选3公里还是5公里？",
    options: [
      { text: "3公里聚焦+提密度", effect: { cash: -100, exposure: 100, badReviewRate: -0.01 },
        knowledge: "知识库：外卖辐射半径不是越大越好，3公里内出餐快、差评低、配送费低。" },
      { text: "拉到5公里", effect: { exposure: 150, badReviewRate: 0.02 },
        knowledge: "远距离配送时间长、温度差、差评率高，得不偿失。" },
      { text: "1公里超近", effect: { exposure: -200 },
        knowledge: "辐射太小订单基数不够，撑不起店铺。" },
    ],
  },
  {
    id: "q068",
    title: "选址房租谈判",
    desc: "看中一个铺位，房东开价是预算的1.5倍。",
    options: [
      { text: "谈降+签3年锁定", effect: { cash: -300 },
        knowledge: "知识库：房租是固定成本黑洞，必须谈降+长期锁定，否则一年涨一次扛不住。" },
      { text: "硬咬牙签1年", effect: { cash: -800 },
        knowledge: "1年到期房东必涨，第二年压力翻倍。" },
      { text: "放弃换次动线", effect: { exposure: -100, cash: 200 },
        knowledge: "次动线也是选择，但要配套引流。" },
    ],
  },
  {
    id: "q069",
    title: "竞品商圈密度",
    desc: "想进的商圈已有3家同品类店。",
    options: [
      { text: "调研3家差异化定位", effect: { cash: -100, enterConversion: 0.005 },
        knowledge: "知识库：商圈有同行不可怕，可怕的是没有差异化。先调研再决定切入点。" },
      { text: "无视直接进", effect: { cash: -300, enterConversion: -0.005 },
        knowledge: "撞同质化=分流量，没人有优势。" },
      { text: "完全避开", effect: { exposure: -100 },
        knowledge: "有同行说明商圈有需求，避开未必明智。" },
    ],
  },
  {
    id: "q070",
    title: "选址冷启动",
    desc: "店开了一周订单还是个位数。",
    options: [
      { text: "三件套：点金+霸王餐+评价启动", effect: { cash: -800, exposure: 300, orderConversion: 0.01, badReviewRate: -0.01 },
        knowledge: "知识库的冷启动SOP：曝光+尝鲜+口碑三件套必须同时上，单兵作战无效。" },
      { text: "等自然流量", effect: { exposure: -100 },
        knowledge: "新店没权重没评价，自然流量趋零。" },
      { text: "全靠朋友圈刷", effect: { exposure: 50 },
        knowledge: "朋友圈量级有限，撑不起持续订单。" },
    ],
  },
  {
    id: "q071",
    title: "配送范围调整",
    desc: "5公里外的订单差评高。",
    options: [
      { text: "缩到4公里+边缘区加配送费", effect: { cash: 100, badReviewRate: -0.02 },
        knowledge: "差评高的远距离单要么砍要么加费，知识库的'优雅止损'。" },
      { text: "保持5公里硬撑", effect: { badReviewRate: 0.02 },
        knowledge: "差评影响整体评分，损失远超远距离单的收益。" },
      { text: "全部砍到3公里", effect: { exposure: -150, badReviewRate: -0.01 },
        knowledge: "砍太狠会丢掉部分稳定单，要分级处理。" },
    ],
  },
  {
    id: "q072",
    title: "夜宵商圈",
    desc: "你在写字楼商圈，夜宵单几乎为0。",
    options: [
      { text: "夜间关店减成本", effect: { cash: 200 },
        knowledge: "知识库：选址决定时段，写字楼商圈夜间没有需求，硬开是亏钱。" },
      { text: "硬撑24小时", effect: { cash: -500, badReviewRate: 0.01 },
        knowledge: "无需求时段开店=纯烧钱。" },
      { text: "上夜宵新菜", effect: { cash: -300 },
        knowledge: "需求不在那里，菜单再变也没用。" },
    ],
  },
  {
    id: "q073",
    title: "选址流量评估",
    desc: "门口看着人多，要怎么验证真实订单潜力？",
    options: [
      { text: "蹲点3天数下单转化", effect: { cash: -100, enterConversion: 0.01 },
        knowledge: "知识库：选址前必须蹲点3天数客流，不能光看人头。" },
      { text: "听房东介绍", effect: { cash: -200 },
        knowledge: "房东永远说自家位置好。" },
      { text: "看竞品销量截图", effect: {},
        knowledge: "截图可能造假，第一手数据最可靠。" },
    ],
  },
  {
    id: "q074",
    title: "扩张第二家",
    desc: "第一家稳定了，要不要开第二家？",
    options: [
      { text: "复制SOP开同类型店", effect: { cash: -1000, exposure: 200 },
        knowledge: "知识库：扩张的前提是SOP成熟+第一家稳定盈利3个月以上。" },
      { text: "盲目开新品类店", effect: { cash: -1500, badReviewRate: 0.02 },
        knowledge: "新品类等于二次创业，不是扩张是赌博。" },
      { text: "暂不扩张", effect: {},
        knowledge: "保守也是策略，但增长会停滞。" },
    ],
  },
  // ========== 七、营销活动 (q075-q087) ==========
  {
    id: "q075",
    title: "霸王餐怎么发",
    desc: "想用霸王餐启动新店。",
    options: [
      { text: "限量50份+只送评分高用户", effect: { cash: -400, exposure: 200, badReviewRate: -0.01 },
        knowledge: "知识库：霸王餐要选高质量种子用户，他们会给你高质量评论。" },
      { text: "无限量送", effect: { cash: -1000, exposure: 250, badReviewRate: 0.02 },
        knowledge: "无限量羊毛党涌入，评论质量低，赔本不讨好。" },
      { text: "不发霸王餐", effect: { exposure: -100 },
        knowledge: "新店冷启动没霸王餐很难快速起评。" },
    ],
  },
  {
    id: "q076",
    title: "代金券和满减选哪个",
    desc: "促销预算只够做一种活动。",
    options: [
      { text: "满减拉客单+引导加购", effect: { cash: -300, exposure: 100, avgPrice: 2, orderConversion: 0.005 },
        knowledge: "知识库：满减比代金券拉客单效率高，是外卖主流活动形态。" },
      { text: "代金券拉新", effect: { cash: -300, orderConversion: 0.005 },
        knowledge: "代金券对老客没新意，对新客转化也一般。" },
      { text: "都不做", effect: { exposure: -50 },
        knowledge: "完全无活动在外卖排名劣势明显。" },
    ],
  },
  {
    id: "q077",
    title: "超值套餐数量",
    desc: "想做几个超值套餐？",
    options: [
      { text: "3个：单人/双人/家庭", effect: { cash: -100, orderConversion: 0.01, avgPrice: 2 },
        knowledge: "知识库：3档套餐覆盖单人/约会/聚餐，比单一套餐转化率更高。" },
      { text: "10个全覆盖", effect: { orderConversion: -0.005 },
        knowledge: "选项过多反而决策瘫痪。" },
      { text: "1个万能套餐", effect: { orderConversion: 0.005 },
        knowledge: "1个套餐缺乏场景区分，用户匹配度差。" },
    ],
  },
  {
    id: "q078",
    title: "拼团活动",
    desc: "想做拼团。",
    options: [
      { text: "2人拼团享8折+独立包装", effect: { cash: -200, exposure: 150, orderConversion: 0.005 },
        knowledge: "外卖拼团核心是社交裂变，独立包装是用户接受拼团的前提。" },
      { text: "10人拼团享5折", effect: { cash: -300, orderConversion: -0.005 },
        knowledge: "10人门槛太高，外卖场景下根本凑不齐。" },
      { text: "不做拼团", effect: {},
        knowledge: "拼团是免费的社交曝光池。" },
    ],
  },
  {
    id: "q079",
    title: "节假日预订",
    desc: "情人节快到了。",
    options: [
      { text: "推情侣套餐+提前一周预热", effect: { cash: -200, exposure: 200, orderConversion: 0.01, avgPrice: 3 },
        knowledge: "知识库：节假日是非常规高客单的窗口，必须提前一周预热抢位。" },
      { text: "当天临时上", effect: { cash: -100, exposure: 50 },
        knowledge: "用户决策已被对手抢走，临时上半个不剩。" },
      { text: "啥都不做", effect: { exposure: -50 },
        knowledge: "节假日是免费流量节点，不参与就是浪费。" },
    ],
  },
  {
    id: "q080",
    title: "短视频投流",
    desc: "想用抖音/小红书投流。",
    options: [
      { text: "本地达人探店+小预算长投", effect: { cash: -500, exposure: 300, enterConversion: 0.005 },
        knowledge: "知识库：本地达人精准+持续曝光是短视频投流的正道，比信息流硬投ROI高。" },
      { text: "信息流硬砸", effect: { cash: -1000, exposure: 200 },
        knowledge: "硬砸缺精准，钱烧得快效果差。" },
      { text: "完全不投", effect: { exposure: -50 },
        knowledge: "不投短视频=放弃年轻用户增量。" },
    ],
  },
  {
    id: "q081",
    title: "直播带货",
    desc: "有人提议做直播卖券。",
    options: [
      { text: "周末固定2小时本地直播", effect: { cash: -300, exposure: 200, orderConversion: 0.005 },
        knowledge: "知识库：本地直播门槛低，固定时段培养习惯比偶尔大场更稳。" },
      { text: "请大主播一次性带", effect: { cash: -1500, exposure: 300, badReviewRate: 0.01 },
        knowledge: "大主播流量虚高，对本地堂食和外卖转化都不稳。" },
      { text: "不做直播", effect: {},
        knowledge: "保守也行，但少一个增量入口。" },
    ],
  },
  {
    id: "q082",
    title: "群发优惠券预算",
    desc: "300元预算群发券。",
    options: [
      { text: "精准发给7天内消费过的老客", effect: { cash: -300, orderConversion: 0.015 },
        knowledge: "知识库：精准推送转化率是泛发的5-10倍，钱要花在刀刃上。" },
      { text: "全用户广撒网", effect: { cash: -300, orderConversion: 0.005 },
        knowledge: "广撒网核销率低，多数人不为所动。" },
      { text: "等节日再发", effect: { exposure: -50 },
        knowledge: "等的过程中老客在流失。" },
    ],
  },
  {
    id: "q083",
    title: "活动复盘频率",
    desc: "做了一波活动，要不要复盘？",
    options: [
      { text: "每周复盘ROI+调整下次", effect: { cash: -50, orderConversion: 0.01 },
        knowledge: "知识库：营销迭代靠复盘，不复盘的活动是赌博。" },
      { text: "凭感觉调", effect: { cash: -200, orderConversion: -0.005 },
        knowledge: "感觉是经验的对立面，迭代效率低。" },
      { text: "不复盘", effect: { orderConversion: -0.01 },
        knowledge: "重复同一种错误烧钱。" },
    ],
  },
  {
    id: "q084",
    title: "联名活动",
    desc: "隔壁咖啡店想和你联名出套餐。",
    options: [
      { text: "试一次互引流", effect: { cash: -200, exposure: 200, enterConversion: 0.005 },
        knowledge: "知识库：异业联名是免费曝光池，关键是用户重叠度高。" },
      { text: "拒绝", effect: { exposure: -30 },
        knowledge: "失去一次免费互流的机会。" },
      { text: "联名但不分账", effect: { cash: -100, badReviewRate: 0.01 },
        knowledge: "不分账=不长久，对方下次不愿合作。" },
    ],
  },
  {
    id: "q085",
    title: "免单抽奖",
    desc: "想做'每日免一单'抽奖。",
    options: [
      { text: "限当日下单参与+次日开奖", effect: { cash: -150, exposure: 100, orderConversion: 0.01 },
        knowledge: "知识库：低成本高悬念的营销动作，1单换100单话题度。" },
      { text: "免单100份大放送", effect: { cash: -1500, exposure: 200, badReviewRate: 0.02 },
        knowledge: "成本翻10倍，效果不翻10倍。" },
      { text: "不做", effect: {},
        knowledge: "错过一种社交话题工具。" },
    ],
  },
  {
    id: "q086",
    title: "会员专属价",
    desc: "想给会员专属低价。",
    options: [
      { text: "招牌菜会员专属-2元", effect: { cash: -150, orderConversion: 0.01, avgPrice: -1 },
        knowledge: "会员专属感比折扣力度更重要，知识库：让会员有'我是特别的'感觉。" },
      { text: "全场会员8折", effect: { cash: -400, avgPrice: -3 },
        knowledge: "全场打折稀释品牌也压客单。" },
      { text: "无会员专属", effect: { orderConversion: -0.005 },
        knowledge: "会员体系无差异=无价值。" },
    ],
  },
  {
    id: "q087",
    title: "活动期外卖vs堂食",
    desc: "活动期间堂食和外卖都要做吗？",
    options: [
      { text: "外卖为主+堂食辅助", effect: { cash: -200, exposure: 150, orderConversion: 0.005 },
        knowledge: "知识库：活动期资源要倾斜到主战场，外卖店主战场就是外卖。" },
      { text: "两线平铺", effect: { cash: -400, badReviewRate: 0.01 },
        knowledge: "资源稀释，两边都做不好。" },
      { text: "只做堂食", effect: { exposure: -200 },
        knowledge: "外卖店放弃外卖=自杀。" },
    ],
  },
  // ========== 八、战略与现金流 (q088-q100) ==========
  {
    id: "q088",
    title: "现金流告急",
    desc: "现金只剩2000了，房租还要交。",
    options: [
      { text: "立即砍非核心成本+保现金", effect: { cash: 300, badReviewRate: 0.005 },
        knowledge: "知识库铁律：现金流是命脉，活下来比什么都重要。" },
      { text: "再砸一波推广博一把", effect: { cash: -800, exposure: 200 },
        knowledge: "现金流告急时押注=赌徒心态，多数赌输。" },
      { text: "继续按原计划走", effect: { cash: -200 },
        knowledge: "不调整=按原节奏走向破产。" },
    ],
  },
  {
    id: "q089",
    title: "成本结构分析",
    desc: "毛利只有20%，问题在哪？",
    options: [
      { text: "拆食材+人工+房租找最大头", effect: { cash: -100, badReviewRate: -0.005 },
        knowledge: "知识库：毛利低必须做成本拆解，找最大头优化，否则瞎调没用。" },
      { text: "猛涨价覆盖成本", effect: { avgPrice: 3, orderConversion: -0.015 },
        knowledge: "涨价压垮转化，营业额掉得比涨价快。" },
      { text: "猛降价冲量", effect: { cash: -300, avgPrice: -3, orderConversion: 0.01 },
        knowledge: "毛利已经低，再降价等于卖一单亏一单。" },
    ],
  },
  {
    id: "q090",
    title: "扩张节奏",
    desc: "第一家月利润6000，要不要立刻开第二家？",
    options: [
      { text: "稳定3个月再开", effect: { cash: 100 },
        knowledge: "知识库：扩张前要让第一家'走自动化'，3个月稳定是基本门槛。" },
      { text: "立刻开", effect: { cash: -1500, badReviewRate: 0.02 },
        knowledge: "第一家还没自动化，第二家会拖垮第一家。" },
      { text: "永不扩张", effect: {},
        knowledge: "也行，但失去增长。" },
    ],
  },
  {
    id: "q091",
    title: "团队招聘",
    desc: "想招一个店长。",
    options: [
      { text: "招有外卖经验+股份激励", effect: { cash: -500, badReviewRate: -0.01, orderConversion: 0.005 },
        knowledge: "知识库：核心岗位用股份绑定，纯工资留不住能干的人。" },
      { text: "招便宜的新人", effect: { cash: -200, badReviewRate: 0.02 },
        knowledge: "便宜的代价是慢慢踩坑，差评和损耗远超工资差。" },
      { text: "自己累点不招", effect: { cash: 100, badReviewRate: 0.01 },
        knowledge: "老板被困在日常里，没时间做真正的经营。" },
    ],
  },
  {
    id: "q092",
    title: "数据看板",
    desc: "经营全靠脑子记，没看板。",
    options: [
      { text: "搭一个简易日报+每日更新", effect: { cash: -100, orderConversion: 0.005 },
        knowledge: "知识库：经营靠数据说话，没有看板=盲驾。" },
      { text: "靠直觉", effect: { orderConversion: -0.005 },
        knowledge: "直觉只在熟悉的水域有效，遇到新问题就翻车。" },
      { text: "全靠平台后台", effect: {},
        knowledge: "平台数据只覆盖一部分，还需自有看板。" },
    ],
  },
  {
    id: "q093",
    title: "竞品监控",
    desc: "隔壁家最近偷偷换菜单。",
    options: [
      { text: "每周固定看3家竞品+做对比", effect: { cash: -50, enterConversion: 0.005 },
        knowledge: "知识库：竞品是免费的研发资源，定期监控让你不掉队。" },
      { text: "无视，自己玩自己的", effect: { enterConversion: -0.005 },
        knowledge: "市场永远在变，闭门造车=被淘汰。" },
      { text: "天天蹲点焦虑", effect: { badReviewRate: 0.005 },
        knowledge: "过度关注竞品会失去自己的节奏。" },
    ],
  },
  {
    id: "q094",
    title: "品牌认知建设",
    desc: "店开半年了，但没什么品牌感。",
    options: [
      { text: "统一VI+招牌slogan+包装", effect: { cash: -400, enterConversion: 0.01, badReviewRate: -0.005 },
        knowledge: "知识库：品牌不是大公司专属，外卖店也需要识别度，不然一直被挑性价比。" },
      { text: "继续无品牌野生", effect: { enterConversion: -0.005 },
        knowledge: "无品牌=每天都在重新自证。" },
      { text: "猛打折买品牌", effect: { cash: -500, avgPrice: -2 },
        knowledge: "打折不会带来品牌只会带来低价标签。" },
    ],
  },
  {
    id: "q095",
    title: "公关危机",
    desc: "一条夸张差评被传到本地论坛。",
    options: [
      { text: "公开诚恳回应+整改方案", effect: { cash: -200, badReviewRate: -0.02, enterConversion: 0.005 },
        knowledge: "知识库：危机公关核心是'透明+行动'，遮掩只会发酵。" },
      { text: "硬刚发律师函", effect: { badReviewRate: 0.03, enterConversion: -0.01 },
        knowledge: "硬刚等于把事件放大，舆论会站到对立面。" },
      { text: "装作没看到", effect: { badReviewRate: 0.02, enterConversion: -0.005 },
        knowledge: "沉默被解读为默认。" },
    ],
  },
  {
    id: "q096",
    title: "学习与提升",
    desc: "老板是一直闷头干还是花时间学习？",
    options: [
      { text: "每周固定半天学+和同行交流", effect: { cash: -100, orderConversion: 0.01 },
        knowledge: "知识库：闷头干的老板会被市场淘汰，学习是最高ROI的投资。" },
      { text: "全力扑业务", effect: { badReviewRate: 0.005 },
        knowledge: "战术勤奋掩盖不了战略懒惰。" },
      { text: "完全不学", effect: { orderConversion: -0.01 },
        knowledge: "市场每年都在变，不学=退步。" },
    ],
  },
  {
    id: "q097",
    title: "停业止损",
    desc: "持续3个月亏损。",
    options: [
      { text: "复盘根因+给自己一个月期限", effect: { cash: -100 },
        knowledge: "知识库：止损要果断，但要有清晰的复盘和最后期限，不能盲目硬扛也不能慌乱关店。" },
      { text: "继续硬扛", effect: { cash: -800, badReviewRate: 0.01 },
        knowledge: "不复盘的硬扛只是在加大损失。" },
      { text: "立刻关店", effect: { cash: -200 },
        knowledge: "没复盘就关，下次开店还会犯同样错误。" },
    ],
  },
  {
    id: "q098",
    title: "供应链优化",
    desc: "想压低食材成本5%。",
    options: [
      { text: "和2个供应商比价+优化品类", effect: { cash: 200, badReviewRate: -0.005 },
        knowledge: "知识库：供应链是系统工程，比价+品类优化是常规动作。" },
      { text: "换最便宜次品", effect: { cash: 300, badReviewRate: 0.03 },
        knowledge: "次品=口感降级=差评爆发，得不偿失。" },
      { text: "什么都不动", effect: {},
        knowledge: "成本只增不减，毛利持续被吃。" },
    ],
  },
  {
    id: "q099",
    title: "用户访谈",
    desc: "想了解为什么老客流失。",
    options: [
      { text: "随机电访10个流失老客", effect: { cash: -100, orderConversion: 0.01, badReviewRate: -0.005 },
        knowledge: "知识库：用户访谈是免费的市场调研，10个真实声音胜过100份后台数据。" },
      { text: "全靠后台数据猜", effect: {},
        knowledge: "数据告诉你'是什么'但不告诉你'为什么'。" },
      { text: "群发问卷", effect: { cash: -50 },
        knowledge: "问卷回收率低，深度不够。" },
    ],
  },
  {
    id: "q100",
    title: "长期主义",
    desc: "短期赚快钱还是慢慢做品牌？",
    options: [
      { text: "守底线+持续打口碑", effect: { cash: -100, badReviewRate: -0.02, orderConversion: 0.01 },
        knowledge: "知识库终极信条：外卖是马拉松不是百米冲刺。守底线、攒口碑、做长期，活到最后才是赢。" },
      { text: "趁机赚一波就跑", effect: { cash: 400, badReviewRate: 0.03 },
        knowledge: "短期赚快钱=透支未来，下一个店没人愿意再来。" },
      { text: "随便经营", effect: { cash: -100, badReviewRate: 0.01 },
        knowledge: "没有定力的店没有未来。" },
    ],
  },
];
